require 'rake/testtask'

Rake::TestTask.new do |t|
  t.pattern = "tests/*_test.rb"
end

task :console do
  require 'pry'
  require 'rest-client'
  root = "http://localhost:4567"
  rc = RestClient
  require_relative 'init'
  binding.pry
end